services:
  - type: web
    name: nids-arc
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: APP_NAME
        value: NIDS ARC
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_MODE
        value: simulation
      - key: APP_SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEFAULT_ADMIN_USERNAME
        value: admin
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
      - key: DEFAULT_ADMIN_EMAIL
        value: sumitdwivedi681@gmail.com
